[package]
name = "cargo_expand_tidy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-expand-tidy"
path = "src/main.rs"

[dependencies]
fxhash = "0.2.1"
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = { version = "1.0.99", features = ["full", "parsing", "printing"] }
